INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES('1', '1', '1', '계정', 'test@test');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES('2', '2', '2', '계정2', 'test2@test2');

IBSERT INTO QUESTION (ID, WRITER, TITLE, CONTENTS, CREATE_DATE) VALUSE(1, 1, '제목', '내용', CURRENT_TIMESTAMP());
IBSERT INTO QUESTION (ID, WRITER, TITLE, CONTENTS, CREATE_DATE) VALUSE(2, 2, '제목2', '내용2', CURRENT_TIMESTAMP());